apiVersion: apps/v1
kind: Deployment
metadata:
  name: pims-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pims-frontend
  template:
    metadata:
      labels:
        app: pims-frontend
    spec:
      containers:
      - name: pims-frontend
        image: irinalexx/pims-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pims-service
spec:
  type: NodePort
  selector:
    app: pims-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
